### ISSUE TITLE
Error en el fichero __main__.py

### ISSUE THREAD

**Issue by JoseVacas** [educollado/neodigit-dyndns#1]
Cuando tiene que actualizar la ip da un error en la linea 51.
`        response = (update_ip(token,domain_info,current_ip))
Defined in neodigit_dyndns/dyndns.py
def update_ip(headers,token,domain_info,current_ip):
`
A la función update_ip se le deberian de pasar 4 argumentos y se le pasan 3. El que falta es el primero, el headers.

**Comment by educollado** [comment]
Muchas gracias, ya está cambiado.

Un saludo
